name: tumy_app
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^2.0.0

  # Images
  image_picker: ^1.1.2
  # APIs
  http: ^1.0.0
  intl: ^0.18.1
  html: ^0.15.4

  # Common packages
  nb_utils: ^6.0.4
  google_fonts: ^5.0.0

  package_info_plus: ^4.0.2

  # Story
  story_view: ^0.16.5
  flutter_reaction_button: ^2.0.1+2

  # State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  firebase_storage: ^12.0.1
  firebase_database: ^11.0.1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0

    #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true


  assets:
    - images/tumy/posts/
    - images/tumy/faces/
    - images/tumy/
    - images/tumy/icons/
    - images/tumy/gifs/




