// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-j0dlJ7o_ziNCYrwoN0W33wdg15rBNdI',
    appId: '1:1085125185652:web:d254eb7cfee099fed78121',
    messagingSenderId: '1085125185652',
    projectId: 'tumy-app',
    authDomain: 'tumy-app.firebaseapp.com',
    databaseURL: 'https://tumy-app-default-rtdb.firebaseio.com',
    storageBucket: 'tumy-app.appspot.com',
    measurementId: 'G-H8H6E0VMRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAefgGSd8Hvczu-S6HU20_WGp-YDo0_nCs',
    appId: '1:1085125185652:android:c864d4afebb6fb9dd78121',
    messagingSenderId: '1085125185652',
    projectId: 'tumy-app',
    databaseURL: 'https://tumy-app-default-rtdb.firebaseio.com',
    storageBucket: 'tumy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblHBVpDwV9DE2ICUwcgwxtvgC5nF7HKY',
    appId: '1:1085125185652:ios:2cc46039fa67bbced78121',
    messagingSenderId: '1085125185652',
    projectId: 'tumy-app',
    databaseURL: 'https://tumy-app-default-rtdb.firebaseio.com',
    storageBucket: 'tumy-app.appspot.com',
    iosBundleId: 'com.tumy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBblHBVpDwV9DE2ICUwcgwxtvgC5nF7HKY',
    appId: '1:1085125185652:ios:2cc46039fa67bbced78121',
    messagingSenderId: '1085125185652',
    projectId: 'tumy-app',
    databaseURL: 'https://tumy-app-default-rtdb.firebaseio.com',
    storageBucket: 'tumy-app.appspot.com',
    iosBundleId: 'com.tumy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-j0dlJ7o_ziNCYrwoN0W33wdg15rBNdI',
    appId: '1:1085125185652:web:786c87a1ef8b2c53d78121',
    messagingSenderId: '1085125185652',
    projectId: 'tumy-app',
    authDomain: 'tumy-app.firebaseapp.com',
    databaseURL: 'https://tumy-app-default-rtdb.firebaseio.com',
    storageBucket: 'tumy-app.appspot.com',
    measurementId: 'G-1N3WP0XE0D',
  );

}